/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inleven;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eliseu
 */
public class HelpRequest extends javax.swing.JFrame {

    private static ObjectOutputStream out = null;
    private static ObjectInputStream in = null;
    ActualState hr = null;
    
    /**
     * Creates new form HelpRequest
     */
    public HelpRequest(ObjectOutputStream out, ObjectInputStream in, ActualState hr) {
        initComponents();
        HelpRequest.out = out;
        HelpRequest.in = in;
        this.hr = hr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jShopping = new javax.swing.JCheckBox();
        jCooking = new javax.swing.JCheckBox();
        jCleaning = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jMatosinhos = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jPorto = new javax.swing.JCheckBox();
        jVNGaia = new javax.swing.JCheckBox();
        jGondomar = new javax.swing.JCheckBox();
        jRioTinto = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jHygiene = new javax.swing.JCheckBox();
        jBlogin = new javax.swing.JButton();
        jExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(362, 350));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("HELP REQUEST");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel1.setText("Localization:");

        jShopping.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jShopping.setText("Shopping");
        jShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShoppingActionPerformed(evt);
            }
        });

        jCooking.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCooking.setText("Cooking");
        jCooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCookingActionPerformed(evt);
            }
        });

        jCleaning.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCleaning.setText("Cleaning");
        jCleaning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCleaningActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setText("Type of request:");

        jMatosinhos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMatosinhos.setText("Matosinhos");
        jMatosinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatosinhosActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCheckBox5.setText("Shopping");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jPorto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPorto.setText("Porto");
        jPorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPortoActionPerformed(evt);
            }
        });

        jVNGaia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jVNGaia.setText("V.N.Gaia");
        jVNGaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVNGaiaActionPerformed(evt);
            }
        });

        jGondomar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jGondomar.setText("Gondomar");
        jGondomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGondomarActionPerformed(evt);
            }
        });

        jRioTinto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRioTinto.setText("Rio Tinto");
        jRioTinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRioTintoActionPerformed(evt);
            }
        });

        jCheckBox10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCheckBox10.setText("Shopping");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jHygiene.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jHygiene.setText("Hygiene");
        jHygiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHygieneActionPerformed(evt);
            }
        });

        jBlogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBlogin.setText("Confirm");
        jBlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBloginActionPerformed(evt);
            }
        });

        jExit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jExit.setText("Back");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jShopping)
                                    .addComponent(jPorto)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jVNGaia))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jMatosinhos)
                                        .addGap(18, 18, 18)
                                        .addComponent(jGondomar))
                                    .addComponent(jRioTinto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCooking)
                                            .addComponent(jHygiene))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox10)
                                            .addComponent(jCleaning))))
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBlogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShopping)
                    .addComponent(jCooking)
                    .addComponent(jCleaning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox10)
                    .addComponent(jHygiene))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPorto)
                    .addComponent(jMatosinhos)
                    .addComponent(jGondomar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVNGaia)
                    .addComponent(jRioTinto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlogin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShoppingActionPerformed
        // TODO add your handling code here:
        hr.helpType = "Shopping";
    }//GEN-LAST:event_jShoppingActionPerformed

    private void jCookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCookingActionPerformed
        // TODO add your handling code here:
        hr.helpType = "Cooking";
    }//GEN-LAST:event_jCookingActionPerformed

    private void jCleaningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCleaningActionPerformed
        // TODO add your handling code here:
        hr.helpType = "cleaning";
    }//GEN-LAST:event_jCleaningActionPerformed

    private void jMatosinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatosinhosActionPerformed
        // TODO add your handling code here:
        hr.local = "Matosinhos";
    }//GEN-LAST:event_jMatosinhosActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jPortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPortoActionPerformed
        // TODO add your handling code here:
        hr.local = "Porto";
    }//GEN-LAST:event_jPortoActionPerformed

    private void jVNGaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVNGaiaActionPerformed
        // TODO add your handling code here:
        hr.local = "VNGaia";
    }//GEN-LAST:event_jVNGaiaActionPerformed

    private void jGondomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGondomarActionPerformed
        // TODO add your handling code here:
        hr.local = "Gondomar";
    }//GEN-LAST:event_jGondomarActionPerformed

    private void jRioTintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRioTintoActionPerformed
        // TODO add your handling code here:
        hr.local = "Rio Tinto";
    }//GEN-LAST:event_jRioTintoActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jHygieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHygieneActionPerformed
        // TODO add your handling code here:
        hr.helpType = "Hygiene";
    }//GEN-LAST:event_jHygieneActionPerformed

    private void jBloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBloginActionPerformed
        // TODO add your handling code here:
        hr.typeRequest = "helprequest";
        if((hr.local == null) || (hr.helpType == null)){
            //do nothing
        }else{
            try {
                out.writeObject(hr);
                out.flush();
                hr = (ActualState) in.readObject();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(HelpRequest.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
            MenuPatient patientMenu = new MenuPatient(out,in,hr);
            patientMenu.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jBloginActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuPatient patientMenu = new MenuPatient(out, in, hr);
        patientMenu.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlogin;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCleaning;
    private javax.swing.JCheckBox jCooking;
    private javax.swing.JButton jExit;
    private javax.swing.JCheckBox jGondomar;
    private javax.swing.JCheckBox jHygiene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jMatosinhos;
    private javax.swing.JCheckBox jPorto;
    private javax.swing.JCheckBox jRioTinto;
    private javax.swing.JCheckBox jShopping;
    private javax.swing.JCheckBox jVNGaia;
    // End of variables declaration//GEN-END:variables
}
